apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: grensekomp
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /health/is-alive
    initialDelay: 10
    timeout: 2
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    path: /health/is-ready
    initialDelay: 10
    timeout: 2
    periodSeconds: 5
    failureThreshold: 10
  ingresses:
    - https://arbeidsgiver.nav.no/grensekomp-api
    - https://grensekomp-api.intern.nav.no
  prometheus:
    enabled: true
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 3500m
      memory: 1000Mi
    requests:
      cpu: 400m
      memory: 200Mi
  leaderElection: false
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true

  accessPolicy:
    outbound:
      external:
        - host: helsearbeidsgiver-proxy.prod-fss-pub.nais.io
        - host: altinn.no
        - host: data.brreg.no

      rules:
        - application: helsearbeidsgiver-proxy
          namespace: helsearbeidsgiver
          cluster: prod-fss

  envFrom:
    # servicebrukerens passord som er  hentet fra vault og lagt inn slik: https://doc.nais.io/security/secrets/kubernetes-secrets/
    - secret: service-user-password-prod
    - secret: altinn-user-password-prod
    - secret: altinn-api-gw-keys-prod
    - configmap: loginservice-idporten # tilgjengeliggjør LOGINSERVICE_IDPORTEN_DISCOVERY_URL og LOGINSERVICE_IDPORTEN_AUDIENCE
  env:
    - name: KOIN_PROFILE
      value: PROD
    - name: DOKARKIV_URL
      value: https://helsearbeidsgiver-proxy.prod-fss-pub.nais.io/dokarkiv
    - name: OPPGAVEBEHANDLING_URL
      value: https://helsearbeidsgiver-proxy.prod-fss-pub.nais.io/oppgave
    - name: PDL_URL
      value: https://helsearbeidsgiver-proxy.prod-fss-pub.nais.io/pdl
    - name: AAREG_URL
      value: https://helsearbeidsgiver-proxy.prod-fss-pub.nais.io/aareg-arbeidsforhold
    - name: ALTINN_ENDPOINT
      value: https://altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternalBasic.svc
    - name: CLAM_AV_URL
      value: http://clamav.clamav.svc.cluster.local/scan
    - name: ALTINN_SERVICE_OWNER_GW_URL
      value: https://api-gw.oera.no/ekstern/altinn/api/serviceowner
    - name: ENHETSREGISTERET
      value: data.brreg.no/enhetsregisteret/api/underenheter
    - name: PROXY_SCOPE
      value: api://prod-fss.helsearbeidsgiver.helsearbeidsgiver-proxy/.default
    - name: KTOR_APPLICATION_BASEPATH
      value: /grensekomp-api
    - name: RUN_BACKGROUND_WORKERS
      value: "false"

  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: grensekomp-db
            diskAutoresize: true
